import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import {
  faArrowRight,
  faArrowLeft,
  faArrowUpRightFromSquare,
  faBolt,
  faBriefcase,
  faBuildingColumns,
  faBullseye,
  faCartShopping,
  faChartLine,
  faCheck,
  faChevronDown,
  faCircleCheck,
  faCircleExclamation,
  faClock,
  faComments,
  faCrown,
  faEarListen,
  faEnvelope,
  faEye,
  faFingerprint,
  faGaugeHigh,
  faGears,
  faGlobe,
  faHandshakeAngle,
  faHeadset,
  faHeartPulse,
  faHotel,
  faLanguage,
  faLightbulb,
  faLocationDot,
  faLock,
  faMapLocationDot,
  faMicrochip,
  faPaperPlane,
  faPhone,
  faQrcode,
  faQuoteLeft,
  faRotate,
  faSatelliteDish,
  faShieldHalved,
  faSitemap,
  faSlidersH,
  faSquarePollVertical,
  faStar,
  faTags,
  faTowerBroadcast,
  faUserGear,
  faUsers,
  faWandMagicSparkles,
  faXmark,
  faBars,
  faDatabase,
  faTriangleExclamation,
} from '@fortawesome/free-solid-svg-icons';
import { faLinkedin } from '@fortawesome/free-brands-svg-icons';

export const ICONS = {
  arrowRight: faArrowRight,
  arrowLeft: faArrowLeft,
  external: faArrowUpRightFromSquare,
  bolt: faBolt,
  briefcase: faBriefcase,
  bank: faBuildingColumns,
  target: faBullseye,
  retail: faCartShopping,
  chart: faChartLine,
  check: faCheck,
  chevronDown: faChevronDown,
  checkCircle: faCircleCheck,
  alert: faCircleExclamation,
  clock: faClock,
  comments: faComments,
  crown: faCrown,
  ear: faEarListen,
  mail: faEnvelope,
  eye: faEye,
  fingerprint: faFingerprint,
  gauge: faGaugeHigh,
  gears: faGears,
  globe: faGlobe,
  handshake: faHandshakeAngle,
  headset: faHeadset,
  health: faHeartPulse,
  hotel: faHotel,
  language: faLanguage,
  idea: faLightbulb,
  pin: faLocationDot,
  lock: faLock,
  map: faMapLocationDot,
  chip: faMicrochip,
  send: faPaperPlane,
  phone: faPhone,
  qr: faQrcode,
  quote: faQuoteLeft,
  loop: faRotate,
  broadcast: faSatelliteDish,
  shield: faShieldHalved,
  sitemap: faSitemap,
  sliders: faSlidersH,
  poll: faSquarePollVertical,
  star: faStar,
  tags: faTags,
  antenna: faTowerBroadcast,
  roles: faUserGear,
  users: faUsers,
  magic: faWandMagicSparkles,
  close: faXmark,
  menu: faBars,
  database: faDatabase,
  warning: faTriangleExclamation,
  linkedin: faLinkedin,
} satisfies Record<string, IconDefinition>;

export type IconName = keyof typeof ICONS;

export function Icon({
  name,
  className = '',
  size,
}: {
  name: IconName;
  className?: string;
  size?: number;
}) {
  return (
    <FontAwesomeIcon
      icon={ICONS[name]}
      className={className}
      style={size ? { fontSize: `${size}px` } : undefined}
    />
  );
}
